[package]
name = "hitsz-ext2-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = "4.5.20"
env_logger = "0.11.5"
fuser = "0.14.0"
libc = "0.2.161"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }

[features]
default = []
